### ISSUE TITLE
Connect container named incorrectly?

### ISSUE THREAD

**Issue by cricket007** [rmoff/rmoff-blog#1]
Hey @rmoff 

Link: https://github.com/rmoff/rmoff-blog/blob/master/content/post/docker-tips-and-tricks-with-ksql-and-kafka.md#deploy-a-kafka-connect-connector-automatically

The connect container is named `kafka-connect` in the Compose network, but the cURL command reaches out to `kafka-connect-worker`. Not sure if that is supposed to be a separate container, so should the cURL be reaching `kafka-connect`, or even `localhost`?

**Comment by rmoff** [comment]
nice catch. I'll fix this, thanks.
