### ISSUE TITLE
Gist not rendered in "Kafka Listeners – Explained"

### ISSUE THREAD

**Issue by beatcracker** [rmoff/rmoff-blog#8]
The [gist with example](https://gist.github.com/rmoff/da2e882a49a55740b242df893e48734f#file-docker-compose-yml) configuration is failed to render, producing `<!-- raw HTML omitted -->`

- https://rmoff.net/2018/08/02/kafka-listeners-explained/
- https://github.com/rmoff/rmoff.github.io/blob/055307badae53f166eb794bc0268d8f016662b48/2018/08/02/kafka-listeners-explained/index.html#L239

#### Screenshot

![image](https://user-images.githubusercontent.com/7583050/171294917-f0e2a5c7-9bbf-4921-8da7-1a7b828ec476.png)

**Comment by rmoff** [comment]
Hi @beatcracker, sorry for the _lengthy_ delay in replying to this. The gist looks like it's rendering just fine now. 
![image](https://user-images.githubusercontent.com/3671582/205884563-fb34695f-459b-409d-a46a-cec235659d43.png)
LMK if you still see issues.
